#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_Q2_KVARN, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q2_KVARN, GGML_TYPE_F16);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_Q2_KVARN, GGML_TYPE_F16);