#include "../fattn-vec.cuh"

DECL_FATTN_VEC_CASE( 64, GGML_TYPE_Q4_KVARN, GGML_TYPE_Q4_KVARN);
DECL_FATTN_VEC_CASE(128, GGML_TYPE_Q4_KVARN, GGML_TYPE_Q4_KVARN);
DECL_FATTN_VEC_CASE(256, GGML_TYPE_Q4_KVARN, GGML_TYPE_Q4_KVARN);
